### ISSUE TITLE
[FR] Add endgame schema validation to detection-rule query - POC1 

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2036]
**Is your feature request related to a problem? Please describe.**
Prebuilt detection rules should support Endgame data for rules that are easily compatible.

**Describe the solution you'd like**
Leveraging the Endgame [eql_schemas/full_schemas.json](https://github.com/elastic/eql-schemas/blob/main/eql_schemas/full_schemas.json) schema, update the query validation to pull in the endgame schema 

**Additional context**
Internal: https://github.com/elastic/security-team/issues/1537

## Tasks
- [ ] Build endgame schema in `QueryValidator`
- [ ] Based on `endgame-*` index, create an endgame schema and validate in `EQLValidator` and `KQLValidator` within `rule_validators`
- [ ] Develop test cases

**Comment by Mikaayenson** [comment]
## Update Discussion with Dan F.

- Endgame Schema : https://github.com/elastic/endgame-sensor/blob/main/Python/endpoint/generators/events/v0/events.yml
- [this repo](https://github.com/elastic/endpoint-eventing-schema) defines the schema (it's not used in any testing but its accurate to the best of our knowledge). examples are here https://github.com/elastic/endpoint-eventing-schema/tree/master/examples

**Comment by Mikaayenson** [comment]
VM Request: https://github.com/elastic/sdh-endgame/issues/632

**Comment by Mikaayenson** [comment]
Sample event

```
{
  "_index": "endgame-4.59.0-000001",
  "_id": "7Ot1TIIBfncJoXQ3Q27-",
  "_version": 1,
  "_score": 0,
  "_source": {
    "@timestamp": 1659140029000,
    "agent": {
      "id": "68b0979a-18b4-4314-a9e2-7b613d1efc89",
      "version": "3.62.2",
      "name": "Endgame",
      "type": "Endgame"
    },
    "ecs": {
      "version": "1.9.0"
    },
    "event": {
      "kind": "event",
      "category": "file",
      "dataset": "file",
      "type": "change",
      "action": "file_rename_event",
      "module": "endgame",
      "sequence": 53320
    },
    "host": {
      "hostname": "DESKTOP-QBBSCUT",
      "name": "DESKTOP-QBBSCUT",
      "id": "68b0979a-18b4-4314-a9e2-7b613d1efc89",
      "ip": "172.27.105.132",
      "os": {
        "family": "windows",
        "name": "Windows",
        "version": "10.0",
        "platform": "windows",
        "type": "windows"
      },
      "user": {
        "domain": "NT AUTHORITY",
        "full_name": "SYSTEM",
        "id": "S-1-5-18",
        "name": "SYSTEM"
      }
    },
    "observer": {
      "hostname": "DESKTOP-QBBSCUT",
      "ip": "172.27.105.132",
      "product": "SMP",
      "vendor": "Endgame",
      "version": "3.27.1",
      "os": {
        "family": "windows",
        "name": "Windows",
        "version": "10.0",
        "platform": "windows",
        "type": "windows"
      }
    },
    "organization": {
      "id": "cce98a4d-653a-48ef-9498-338cfc8886f6",
      "name": "Elastic Endgame"
    },
    "user": {
      "domain": "NT AUTHORITY",
      "full_name": "SYSTEM",
      "id": "S-1-5-18",
      "name": "SYSTEM"
    },
    "file": {
      "directory": "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\NonCritical_Update;_b0be471ff025c81439b4df72b86015e802fc947_00000000_0496163b\\",
      "drive_letter": "C",
      "extension": "wer",
      "name": "Report.wer",
      "path": "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\NonCritical_Update;_b0be471ff025c81439b4df72b86015e802fc947_00000000_0496163b\\Report.wer",
      "uid": "S-1-5-18",
      "code_signature": {
        "exists": false
      },
      "hash": {
        "md5": "7202ec0bdedff4bcd41a4296eff5e6ff",
        "sha1": "e6e6abb7181aae5bbe22912dc5b6a1184a848746",
        "sha256": "ef69ad2c81e8b5160666d21b1369211c63430d778338d8ab40edcdad663bcb84"
      }
    },
    "process": {
      "executable": "C:\\Windows\\System32\\wermgr.exe",
      "name": "wermgr.exe",
      "title": "wermgr.exe",
      "pid": 17580
    },
    "related": {
      "hash": [
        "7202ec0bdedff4bcd41a4296eff5e6ff",
        "e6e6abb7181aae5bbe22912dc5b6a1184a848746",
        "ef69ad2c81e8b5160666d21b1369211c63430d778338d8ab40edcdad663bcb84"
      ],
      "hosts": [
        "DESKTOP-QBBSCUT",
        "NT AUTHORITY"
      ],
      "ip": [
        "172.27.105.132"
      ],
      "user": [
        "SYSTEM"
      ]
    },
    "endgame": {
      "event_subtype_full": "file_rename_event",
      "event_type_full": "file_event",
      "opcode": 3,
      "pid": 17580,
      "process_name": "wermgr.exe",
      "process_path": "C:\\Windows\\System32\\wermgr.exe",
      "serial_event_id": 53320,
      "unique_pid": 53265,
      "user_domain": "NT AUTHORITY",
      "user_name": "SYSTEM",
      "user_sid": "S-1-5-18",
      "file_path": "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\NonCritical_Update;_b0be471ff025c81439b4df72b86015e802fc947_00000000_0496163b\\Report.wer",
      "file_name": "Report.wer",
      "old_file_path": "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\NonCritical_Update;_b0be471ff025c81439b4df72b86015e802fc947_00000000_0496163b\\Report.wer.tmp",
      "old_file_name": "Report.wer.tmp",
      "md5": "7202ec0bdedff4bcd41a4296eff5e6ff",
      "sha1": "e6e6abb7181aae5bbe22912dc5b6a1184a848746",
      "sha256": "ef69ad2c81e8b5160666d21b1369211c63430d778338d8ab40edcdad663bcb84",
      "timestamp_utc": "2022-07-30 00:13:49Z",
      "timestamp": 133036136294075660
    }
  },
  "fields": {
    "endgame.event_type_full": [
      "file_event"
    ],
    "file.path": [
      "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\NonCritical_Update;_b0be471ff025c81439b4df72b86015e802fc947_00000000_0496163b\\Report.wer"
    ],
    "endgame.sha1": [
      "e6e6abb7181aae5bbe22912dc5b6a1184a848746"
    ],
    "event.category": [
      "file"
    ],
    "endgame.serial_event_id": [
      53320
    ],
    "process.name.text": [
      "wermgr.exe"
    ],
    "endgame.event_subtype_full": [
      "file_rename_event"
    ],
    "host.os.name.text": [
      "Windows"
    ],
    "related.hash": [
      "7202ec0bdedff4bcd41a4296eff5e6ff",
      "e6e6abb7181aae5bbe22912dc5b6a1184a848746",
      "ef69ad2c81e8b5160666d21b1369211c63430d778338d8ab40edcdad663bcb84"
    ],
    "host.hostname": [
      "DESKTOP-QBBSCUT"
    ],
    "process.pid": [
      17580
    ],
    "observer.os.version": [
      "10.0"
    ],
    "endgame.user_name": [
      "SYSTEM"
    ],
    "process.title.text": [
      "wermgr.exe"
    ],
    "observer.vendor": [
      "Endgame"
    ],
    "host.user.full_name.text": [
      "SYSTEM"
    ],
    "endgame.old_file_name": [
      "Report.wer.tmp"
    ],
    "host.os.version": [
      "10.0"
    ],
    "user.full_name.text": [
      "SYSTEM"
    ],
    "endgame.timestamp": [
      133036136294075660
    ],
    "host.os.name": [
      "Windows"
    ],
    "host.user.name": [
      "SYSTEM"
    ],
    "endgame.process_path": [
      "C:\\Windows\\System32\\wermgr.exe"
    ],
    "agent.name": [
      "Endgame"
    ],
    "host.name": [
      "DESKTOP-QBBSCUT"
    ],
    "event.kind": [
      "event"
    ],
    "endgame.user_sid": [
      "S-1-5-18"
    ],
    "file.path.text": [
      "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\NonCritical_Update;_b0be471ff025c81439b4df72b86015e802fc947_00000000_0496163b\\Report.wer"
    ],
    "observer.os.type": [
      "windows"
    ],
    "host.os.type": [
      "windows"
    ],
    "user.id": [
      "S-1-5-18"
    ],
    "observer.os.platform": [
      "windows"
    ],
    "endgame.opcode": [
      3
    ],
    "host.user.name.text": [
      "SYSTEM"
    ],
    "related.user": [
      "SYSTEM"
    ],
    "process.name": [
      "wermgr.exe"
    ],
    "endgame.process_name": [
      "wermgr.exe"
    ],
    "agent.id": [
      "68b0979a-18b4-4314-a9e2-7b613d1efc89"
    ],
    "observer.version": [
      "3.27.1"
    ],
    "ecs.version": [
      "1.9.0"
    ],
    "organization.id": [
      "cce98a4d-653a-48ef-9498-338cfc8886f6"
    ],
    "user.full_name": [
      "SYSTEM"
    ],
    "agent.version": [
      "3.62.2"
    ],
    "file.extension": [
      "wer"
    ],
    "related.hosts": [
      "DESKTOP-QBBSCUT",
      "NT AUTHORITY"
    ],
    "process.title": [
      "wermgr.exe"
    ],
    "host.os.family": [
      "windows"
    ],
    "observer.ip": [
      "172.27.105.132"
    ],
    "endgame.file_path": [
      "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\NonCritical_Update;_b0be471ff025c81439b4df72b86015e802fc947_00000000_0496163b\\Report.wer"
    ],
    "file.hash.md5": [
      "7202ec0bdedff4bcd41a4296eff5e6ff"
    ],
    "user.name": [
      "SYSTEM"
    ],
    "file.uid": [
      "S-1-5-18"
    ],
    "file.hash.sha1": [
      "e6e6abb7181aae5bbe22912dc5b6a1184a848746"
    ],
    "event.sequence": [
      53320
    ],
    "host.ip": [
      "172.27.105.132"
    ],
    "agent.type": [
      "Endgame"
    ],
    "observer.os.name.text": [
      "Windows"
    ],
    "process.executable.text": [
      "C:\\Windows\\System32\\wermgr.exe"
    ],
    "event.module": [
      "endgame"
    ],
    "related.ip": [
      "172.27.105.132"
    ],
    "file.hash.sha256": [
      "ef69ad2c81e8b5160666d21b1369211c63430d778338d8ab40edcdad663bcb84"
    ],
    "endgame.user_domain": [
      "NT AUTHORITY"
    ],
    "observer.product": [
      "SMP"
    ],
    "user.domain": [
      "NT AUTHORITY"
    ],
    "host.user.id": [
      "S-1-5-18"
    ],
    "host.id": [
      "68b0979a-18b4-4314-a9e2-7b613d1efc89"
    ],
    "endgame.md5": [
      "7202ec0bdedff4bcd41a4296eff5e6ff"
    ],
    "process.executable": [
      "C:\\Windows\\System32\\wermgr.exe"
    ],
    "file.directory": [
      "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\NonCritical_Update;_b0be471ff025c81439b4df72b86015e802fc947_00000000_0496163b\\"
    ],
    "observer.os.family": [
      "windows"
    ],
    "endgame.old_file_path": [
      "C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportQueue\\NonCritical_Update;_b0be471ff025c81439b4df72b86015e802fc947_00000000_0496163b\\Report.wer.tmp"
    ],
    "file.name": [
      "Report.wer"
    ],
    "endgame.pid": [
      17580
    ],
    "organization.name": [
      "Elastic Endgame"
    ],
    "host.user.domain": [
      "NT AUTHORITY"
    ],
    "endgame.file_name": [
      "Report.wer"
    ],
    "endgame.timestamp_utc": [
      "2022-07-30 00:13:49Z"
    ],
    "observer.hostname": [
      "DESKTOP-QBBSCUT"
    ],
    "organization.name.text": [
      "Elastic Endgame"
    ],
    "endgame.sha256": [
      "ef69ad2c81e8b5160666d21b1369211c63430d778338d8ab40edcdad663bcb84"
    ],
    "file.drive_letter": [
      "C"
    ],
    "host.user.full_name": [
      "SYSTEM"
    ],
    "observer.os.name": [
      "Windows"
    ],
    "event.action": [
      "file_rename_event"
    ],
    "@timestamp": [
      "2022-07-30T00:13:49.000Z"
    ],
    "host.os.platform": [
      "windows"
    ],
    "file.code_signature.exists": [
      false
    ],
    "event.type": [
      "change"
    ],
    "endgame.unique_pid": [
      53265
    ],
    "event.dataset": [
      "file"
    ],
    "user.name.text": [
      "SYSTEM"
    ]
  }
}
```

**Comment by Mikaayenson** [comment]
Closing in favor of [POC 2](https://github.com/elastic/detection-rules/issues/2252) that will continue in 8.5!
