### ISSUE TITLE
[FR] POC1 Add endgame schema support to detection-rule query validation

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2252]
**Is your feature request related to a problem? Please describe.**
Prebuilt detection rules should support Endgame data for rules that are easily compatible.

**Describe the solution you'd like**
Leveraging the Endgame mapping.json obtained from the Endgame mapping.json, update the query validation to pull in the endgame schema 

<img width="1575" alt="image (1)" src="https://user-images.githubusercontent.com/1636709/185480576-7731d1fc-c740-4edf-82d6-1689df540410.png">

**Additional context**
Internal: https://github.com/elastic/security-team/issues/1537

## Tasks
- [ ] Build endgame schema in `QueryValidator`
- [ ] Based on `endgame-*` index, create an endgame schema and validate in `EQLValidator` and `KQLValidator` within `rule_validators`
- [ ] Develop test cases

**Comment by Mikaayenson** [comment]
@brokensound77 One thing I noticed as I was developing the logic for this mapping.json in the [PR](https://github.com/elastic/detection-rules/issues/2252) is that the original `mapping.json` file had a `process.entity_id` key.

![Screen Shot 2022-08-22 at 3 37 24 PM](https://user-images.githubusercontent.com/1636709/186004757-a60f5ba4-f8ce-4cd9-a49e-cf98fd9ac544.png)

From my understanding, this key has not yet been added to the mapping, so I'm not sure if this file is accurate.
