### ISSUE TITLE
[Rule Tuning] 8.8 Linux Rule Tuning Reviews

### ISSUE THREAD

**Issue by shashank-elastic** [elastic/detection-rules#2544]
## Description
A detailed Analysis of Linux Rule Tunings over the releases has been documented [here](https://docs.google.com/spreadsheets/d/1oA7vlsqTzm6pg6A6LPNhx6uzV-ClFlD3hP9qSVwu0O4/edit?usp=sharing) 

Review Rules Guide Lines.

1. Check for False Positive(s) of Rule Firing.
2. Look if Rule Index is pointing to the right log structures.
3. Check Rule Semantics like Tags Naming and MITRE Mapping --> Mostly Caught in Unit Tests, but good to have checks
4. On High False Positives Tune the Rule Logic to excluded and tighten the detection criteria.

Following Rules have to be reviewed for Tuning in 8.8

- [x] 1. credential_access_bruteforce_password_guessing (good)
- [x] 2. credential_access_potential_linux_ssh_bruteforce (tuned in #2583) 
- [x] 3. credential_access_potential_linux_ssh_bruteforce_root (fixed in #2595)
- [x] 4. defense_evasion_chattr_immutable_file #2753 
- [x] 5. defense_evasion_hidden_shared_object (tuned in #2596)
- [x] 6. execution_process_started_from_process_id_file (good)
- [x] 7. execution_reverse_shell_via_named_pipe (good)
- [x] 8. execution_tc_bpf_filter (good)
- [ ] 9. impact_process_kill_threshold (waiting for feedback on type change bypass)
- [x] 10. persistence_chkconfig_service_add (good)
- [x] 11. persistence_dynamic_linker_backup (good)
- [x] 12. persistence_insmod_kernel_module_load (good)
- [x] 13. privilege_escalation_shadow_file_read (tuned in #2594)
- [x] 14. privilege_escalation_unshare_namesapce_manipulation (changed filename #2599)

Following Rules need round 2 Iteration Of Tuning

- [x] 1. execution_abnormal_process_id_file_created (tuned in #2600)
- [x] 2. execution_shell_evasion_linux_binary (tuned in #2686) Awk family was tuned and new process detections added.
- [x] 3. persistence_shell_activity_by_web_server (tuned in #2585)

The below Rules have been fixed in previous release, they need to re-checked for tuning and updated accordingly.

- [x] 1. persistence_etc_file_creation #2753 

Similar Issues reported Community 

- [x] #2539
- [x] #2543

Note : Update the excel sheet according with the tuning details that can help us track for future releases
