### ISSUE TITLE
[FR] Add release-docs workflow

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2743]
# Summary

While we wait for our [permanent docs home](https://github.com/elastic/ia-trade-team/issues/120), we can refine our release workflow to cleanup a few steps in our release process.

```[tasklist]
# Tasks
- [ ] Create release docs workflow to security-docs that can run from a specific branch
- [ ] The steps will include 1) bump package, 2) build-release and 3) build-integrations-docs
- [ ] Update build-integration-docs to auto modify files correct and put strings where they need to be (per the [release docs process](https://github.com/elastic/ia-trade-team/wiki/Detection-Rules-Releasing-v2)).
```
