### ISSUE TITLE
[FR] Building Block Rules: DED

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2802]
# Issue

https://github.com/elastic/ia-trade-team/issues/70

# Summary

The purpose of this is to support the BBR feature within detection-rules.

```[tasklist]
# Tasks
- [x] Create a new directory `bbr_rules` to store BBR
- [x] Add unit test to ensure `if building_block_type`, verify in bbr_rules/`
- [x] Update tests base class to filter BBR rules.
- [x] Handle BBR exceptions based on metadata and exempt in unit tests
- [ ] Enforce the BBR Rule defaults to fire 60m except by exception (check fields like interval loopback or maxspan in the query )
```

## Additional Context

* [REF](https://www.elastic.co/guide/en/security/current/building-block-rule.html)
* discussion [doc](https://docs.google.com/document/d/1-ppk3tuzT09hemSBDbgn1bZGXfam5yfXtGy97XiAIuo/edit#heading=h.ujhvhxnxxwux)

**Comment by eric-forte-elastic** [comment]
The current PR implementation assumes that the BBR should be exempt from the following unit tests:

- https://github.com/elastic/detection-rules/blob/05aac4f371cc946d6a43d81088a71e2c5ca55992/tests/test_all_rules.py#L58
