### ISSUE TITLE
[Bug] Non Public Fields Not Stripped on Future Builds

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2931]
**Describe the bug**

Based on a [discussion](https://elasticstack.slack.com/archives/C016E72DWDS/p1689454951219379) in our community slack, we've identified some fields are inadvertently not stripped before using the public API. This occurs when trying to use rules on a future stack.

**To Reproduce**
1. Go to an old branch in our repo
2. Use a later stack 
3. Run the `upload-rule` command

<details><summary>Sample Error</summary>
<p>

```
{"statusCode":400,"error":"Bad Request","message":"[request body]: invalid keys \"related_integrations,[{\"package\":\"windows\",\"version\":\"^1.5.0\"}],required_fields,[{\"name\":\"event.category\",\"type\":\"keyword\",\"ecs\":true},{\"name\":\"host.os.type\",\"type\":\"keyword\",\"ecs\":true},{\"name\":\"powershell.file.script_block_text\",\"type\":\"unknown\",\"ecs\":false}]\""}
``` 

</p>
</details> 

**Expected behavior**

You should be able to successfully upload the rule as expected.

```[tasklist]
### Tasks
- [ ] Build a global variable in definitions to track NON_PUBLIC_FIELDS
- [ ] Create a method in schemas/__init__.py to take a dict object of the rule and remove the non public fields.
- [ ] Call the method in the upload-rule CLI command before passing to the downgrade method.
``` 

**Additional context**
Related to https://github.com/elastic/detection-rules/pull/2707
