### ISSUE TITLE
[Meta] Linux Ransomware Analysis - Cl0p & BlackCat

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#2936]
## Summary
Dynamic/Static analysis of most recent blackcat, cl0p, and royal ransomware samples to identify unique characteristics across the entirety of the MITRE ATT&CK matrix.

```[tasklist]
### Tasks
- [ ] collect and study public documentations (blogs, whitepapers etc.) - week 1
- [ ] collect samples - week 1
- [ ] test coverage and identify gaps - week 1/2
- [ ] tune or write new rules - week 2
```

## Goals
- Based on analysis of the research papers, do we detect these samples' initial access vectors? 
- Do we have detection rules in place to capture all of their persistence mechanisms in a fresh environment with prebuilt rules enabled?
- Do we have detections in place to capture their defense evasion techniques? Do we even capture their defense evasion techniques? 
- Do we have endpoint rules and/or detection rules in place to capture their encryption / ransomware activities?
- Do we find any new detection opportunities for discovery, collection, command and control and/or exfiltration activity?

## Resources:
https://www.sentinelone.com/labs/cl0p-ransomware-targets-linux-systems-with-flawed-encryption-decryptor-available/
