### ISSUE TITLE
[Meta] Masquareding and Suspicious Child Processes on Business Apps

### ISSUE THREAD

**Issue by w0rk3r** [elastic/detection-rules#2938]
## Summary

Explore opportunities to detect masquerading and suspicious processes on commonly used business apps such as communication apps, browsers, and Windows native applications and processes.

```[tasklist]
### Tasks
- [ ] Select a pool of Communication Apps to get started - Week 1
- [ ] Select a pool of Browsers to get started - Week 1
- [ ] Search for blogs, papers, or talks around masquerading and signature anomalies - Week 1
- [ ] Search for previous vulnerable versions and exploits on communications apps, try to simulate - Week 1/2
- [ ] Look for malware score matches on processes matching communication app names, detonate them - Week 1
- [ ] Look at ER/DR alerts matching communication app names - Week 1/2
- [ ] Analyze Windows Signatures on specific paths, such as system32 - Week 2
- [ ] Write new rules - Weeks 1 & 2
```

## Goals

- Cover Scenarios where attackers abuse stolen certificates to sign trojanized applications and installers
- Introduce BBRs to gather data and baseline these application behaviors, after excluding common ones.
- Introduce initial coverage around suspicious installers that can be part of malicious Ad campaigns or that try to impersonate legitimate apps.

## Resources:

https://blogs.blackberry.com/en/2023/06/romcom-resurfaces-targeting-ukraine

**Comment by brokensound77** [comment]
Has progress been started on this @w0rk3r? Any status updates?

**Comment by w0rk3r** [comment]
Closing this one as completed, the only task scoped which I'm postponing to a second phase is the malware score one. Once we promote the new BBR rules and have enough telemetry I'll work on it.
