### ISSUE TITLE
[Meta] Linux RAD and DED Tasks

### ISSUE THREAD

**Issue by shashank-elastic** [elastic/detection-rules#2947]
## Summary
Adhoc Linux RAD and DED Taks for Sprint July 24 2023- Aug 4 2023

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/security-team/issues/7166 - 2 day Task completion by 26 July 2023
- [ ] https://github.com/elastic/detection-rules/issues/2911
- [ ] https://github.com/elastic/react/issues/59
- [ ] Tuning Overview for Endpoint Rules Linux. Get Metasheet up to date Like Detection and cross-check all rules.  _<< Issue coming up>>_
```

## Goals
- Complete all tasks listed.
- Flag any overshooting tasks for the next sprint.
- Document any new rule dev work that could be forked based on Rule Tuning Analysis.

**Comment by DefSecSentinel** [comment]
Not needed as sprint Meta issues are already being tracked on RAD and DED boards respectively.
