### ISSUE TITLE
[FR] Create ESQL Stack to test Validation API

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#2948]
# Summary

Based on our [initial discussion](https://github.com/elastic/detection-rules/issues/2481), we need to explore additional validation for the new ESQL language.

```[tasklist]
### Tasks
- [ ] Create an ESQL stack and share info with the team
- [ ] Explore the validation API per our [initial investigation](https://github.com/elastic/detection-rules/issues/2481#issuecomment-1631139720).
- [ ] Design new workflow to use the validation in our CI workflows.
```

**Comment by brokensound77** [comment]
can we close this out as complete @Mikaayenson

**Comment by Mikaayenson** [comment]
@brokensound77 sure can. @terrancedejesus completed this [here](https://github.com/elastic/ia-trade-team/issues/163#issuecomment-1792738693)
