### ISSUE TITLE
[Meta] Linux Privilege Escalation Research & Detection Engineering

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#2955]
## Summary
Analyze commonly exploited linux privilege escalation vectors, research the methodology required to exploit those vectors and analyze whether we can detect these vectors, and if not, create detection rules to cover our detection gaps. 

```[tasklist]
### Tasks
- [x] Identify a set of linux privilege escalation vectors that we currently have no coverage for (week 1-2)
- [x] Exploit and research these privilege escalation vectors (week 1-2)
- [x] Write DRs for these coverage gaps (week 1-2)
- [x] Get PRs merged
```

## Goals
- Identify a set of linux privilege escalation vectors that we currently do not detect.
- Identify whether we can create detection rules for these vectors, and if so, create these DRs.
- DRs with little to no FPs will be (or will be in the future) converted to ERs.

## Resources:
https://www.rgrosec.com/post/2022-02-17-linux-privilege-escalation.html
https://book.hacktricks.xyz/linux-hardening/privilege-escalation
https://github.com/carlospolop/PEASS-ng/tree/master/linPEAS
https://github.com/rebootuser/LinEnum

## PRs
- https://github.com/elastic/detection-rules/pull/2946
- https://github.com/elastic/detection-rules/pull/2945
- https://github.com/elastic/detection-rules/pull/2956
- https://github.com/elastic/detection-rules/pull/2966
- https://github.com/elastic/detection-rules/pull/2969
- https://github.com/elastic/detection-rules/pull/2970
- https://github.com/elastic/detection-rules/pull/2965
- https://github.com/elastic/detection-rules/pull/2960
- https://github.com/elastic/detection-rules/pull/2958
- https://github.com/elastic/detection-rules/pull/2970
- https://github.com/elastic/detection-rules/pull/2971
- https://github.com/elastic/detection-rules/pull/2973
- https://github.com/elastic/detection-rules/pull/2974
- https://github.com/elastic/endpoint-rules/pull/2587
- https://github.com/elastic/detection-rules/pull/2982
- https://github.com/elastic/detection-rules/pull/2983
- https://github.com/elastic/detection-rules/pull/2984

**Comment by brokensound77** [comment]
Just did a review of all pending rules 👍, great job
