### ISSUE TITLE
[Meta] Linux Tunneling and Port Forwarding Research & Detection Engineering

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#2989]
## Summary
Analyze commonly used methods for tunneling and port forwarding on Linux, find anomalies in these methods, test whether we can detect these methods and if not, create detection rules to cover our detection gaps. 

```[tasklist]
### Tasks
- [x] Identify a set of Linux tunneling and port forwarding methods that we currently have no coverage for (week 1-2)
- [x] Research these tunneling and port forwarding methods (week 1-2)
- [x] Write DRs for these coverage gaps (week 1-2)
- [x] Get PRs merged
```

## Goals
- Identify a set of linux tunneling and port forwarding methods that we currently do not detect.
- Identify whether we can create detection rules for these methods, and if so, create these DRs.
- DRs with little to no FPs will be (or will be in the future) converted to ERs.

## Resources:
https://book.hacktricks.xyz/generic-methodologies-and-resources/tunneling-and-port-forwarding

## PRs
https://github.com/elastic/detection-rules/pull/3028
