### ISSUE TITLE
[Meta] MacOS Detection Rule Review and New Rule Backlog

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#2996]
```[tasklist]
      #### Week 1 
- [x] Review macOS detection rules and evaluate rule value along with need for tuning, BBR conversion or deprecation
- [x] Action macOS detection rules review results
```
```[tasklist]
      #### Week 2 
- [ ] Create new detection rules from macOS DR and deprecation backlog
```

## Goals
Assess our macOS detection rules and clean them up

**Comment by DefSecSentinel** [comment]
Due to me having short weeks and being out a bunch during this sprint I was able to achieve only half of what I wanted to with this Meta and would like to continue it during the next sprint. This Meta is more of a maintenance Meta so its not work being relied upon to be completed in a specific timespan but it's work that needs to get done.
