### ISSUE TITLE
[Meta] Linux Metasploit Module Research & Detection Engineering

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#3044]
## Summary
Analyze the current list of Metasploit privilege escalation and persistence modules for Linux, test whether we can detect these methods (via Metasploit or manually), and if not, create detection rules to cover our detection gaps. 

```[tasklist]
### Tasks
- [ ] Identify a set of Metasploit privilege escalation / persistence methods that we currently have no coverage for (week 1-2)
- [ ] Research these Metasploit privilege escalation / persistence methods (week 1-2)
- [ ] Write DRs for these coverage gaps (week 1-2)
- [ ] Get PRs merged
```

## Goals
- Identify a set of Linux Metasploit privilege escalation and persistence modules that we currently do not detect.
- Identify whether we can create detection rules for these methods, and if so, create these DRs.
- DRs with little to no FPs will be (or will be in the future) converted to ERs.

## Resources:
https://github.com/rapid7/metasploit-framework/tree/master/modules

**Comment by Aegrah** [comment]
This one will have no priority in the upcoming sprints, so I will close it for now.
