### ISSUE TITLE
[Meta] Review Detection Rules for Mitre Mapping Coverage Improvements

### ISSUE THREAD

**Issue by w0rk3r** [elastic/detection-rules#3098]
### Summary

With our new Mitre Att&ck coverage map, we need to review our ruleset to do our best to reflect our real coverage in our mappings.

```[tasklist]
### Tasks
- [x] Review recently added techniques on recent Att&ck releases
- [x] Review the Windows ruleset for mapping improvements (Reduced the scope)
- [x] PR to detection-rules
```

**Comment by w0rk3r** [comment]
The reviews were added to https://github.com/elastic/detection-rules/pull/3165, which was merged. Closing this as completed
