### ISSUE TITLE
[Epic] UEBA Package through Detection Rules

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#3099]
## Summary
This Epic will be used to track the work done across the team regarding the UEBA through detection rules project. We will explore the usage of detection rules (with a main focus on new_terms rules) to chain suspicious behavior together and assign risk to entities. This will be phase 1 of this research, and will focus on creating a design doc / PoC, and ship out a first version to gather telemetry. After which this can be used as input for the rest of the team to build upon and create new Metas for different entities. 

More Epics/Metas will be created once more information is available. 

Most progress is being tracked in [Approach to UEBA- V0.1](https://docs.google.com/document/d/1xdy2nw3NXQ-Sy7aJQ6sDAzosJZC28u58MWFBKER-rms/edit)

```[tasklist]
### Tasks
- [x] [Meta (Partially finished)] Research into leveraging detection rules as the main approach for UEBA functionality and creating an elaborate overview of this research, to share with TRaDE, MLSec and other stakeholders.
- [x] [Meta (In Progress)] Create PoC to ship to production, to test functionality and aid in telemetry gathering.
- [ ] [Multiple Metas] Based on the outcome of the PoC, create a set of Metas for team members to join in on the UEBA project and build similar packs for different entities.
```

## Metas
[[Meta] UEBA/EA via Detection Engineering Approach Design/PoC #3086](https://github.com/elastic/detection-rules/issues/3086) 
[[Meta] UEBA Pack for Suspicious Discovery User Activity #3105](https://github.com/elastic/detection-rules/issues/3105)
[[Meta] UEBA Pack for Suspicious Execution User Activity #3106](https://github.com/elastic/detection-rules/issues/3106)
[[Meta] Github Detection Rules and Research #164](https://github.com/elastic/ia-trade-team/issues/164)
[[Meta] [Design] TRaDE Approach To UEBA for Use-Case: Github](https://github.com/elastic/ia-trade-team/issues/165
)

## References
[Infosec UEBA approach for GitHub](https://github.com/elastic/infosec/issues/14676)
[Overall Infosec Meta](https://github.com/elastic/infosec/issues/14322)
[Advanced Analytics Pack notes](https://docs.google.com/document/d/1jaEUZ1RRGE7clMQ-qys27REjMhpA3gnidGxV6a7arng/edit)
[Pros/Cons detection rule approach](https://docs.google.com/document/d/1C1S1gwMximoroy_CAF06ZETBT5tv9XqgpRcEXHXZqkI/edit#heading=h.2ixaw3acewt5)
