### ISSUE TITLE
[BBR] MacOS BBR Evaluation and Conversion

### ISSUE THREAD

**Issue by DefSecSentinel** [elastic/detection-rules#3101]
```[tasklist]
### Tasks
- [ ] Review the list below [BBR Spreadsheet](https://docs.google.com/spreadsheets/d/1NrGmglSmI3m7tqzFJgEFPipFQ_qx5V5lt3rDf6eeG3c/edit?usp=sharing)
- [ ] Push New Rules and Tunings to DR
- [ ] Add justifications to the ones that we don't convert
```

Reviewed and Converted:

* [ ] [Launch-Daemon-Persistence](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/Launch-Daemon-Persistence.toml)
* [ ] [Loading-Kernel-Modules-with-kextload](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/Loading-Kernel-Modules-with-kextload.toml)
* [ ] [MacOS-File-Masquerading](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/MacOS-File-Masquerading.toml)
* [ ] [MacOS-Privilege-Escalation-via-Sudo-Caching](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/MacOS-Privilege-Escalation-via-Sudo-Caching.toml)
* [ ] [Password-Policy-Enumeration](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/Password-Policy-Enumeration.toml)
* [ ] [Persistence-via-Kernel-Extension-Modification](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/Persistence-via-Kernel-Extension-Modification.toml)
* [ ] [Plist-Modification](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/Plist-Modification.toml)
* [ ] [Reading-the-Clipboard-with-pbpaste](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/Reading-the-Clipboard-with-pbpaste.toml)
* [ ] [Screenshot-command-used-with-MacOS](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/Screenshot-command-used-with-MacOS.toml)
* [ ] [Suspicious-JAR-Descendant-Process](https://github.com/elastic/mitre-eval-2022/blob/main/non_prod_rules/old/Suspicious-JAR-Descendant-Process.toml)
