### ISSUE TITLE
[Meta] UEBA Pack for Suspicious Discovery User Activity 

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#3105]
## Summary
This Meta will focus on building out an initial UEBA detection rule pack for Discovery-related Windows rules. 

```[tasklist]
### Tasks
- [x] Identify a list of interesting detections for a Discovery-related Windows UEBA detection rule pack and create an overview.
- [x] Based on the overview - identify any detection rules that we already have available within our detection_rules repo, and identify which ones we still have to create.
- [x] Analyze telemetry for the detection rules that we have available. If necessary, tune the rules or convert to new_terms to reduce noise.
- [x] Create threshold rules to query the results of the created detection rules, and alert depending on a combination of potential vectors.
- [ ] Get the PR with rule tunings, new rules and overall threshold rule for UEBA pack merged.
```

Most progress is being tracked in [Approach to UEBA- V0.1](https://docs.google.com/document/d/1xdy2nw3NXQ-Sy7aJQ6sDAzosJZC28u58MWFBKER-rms/edit)

## Issues
https://github.com/elastic/detection-rules/pull/3097
https://github.com/elastic/detection-rules/issues/3093

## Tuning & analysis
The tuning for the Discovery related rules is now available as PR at #3097. Additionally, several new rules have been created in #3112.

**Comment by Aegrah** [comment]
The tuning for the Discovery related rules is now available as PR at https://github.com/elastic/detection-rules/pull/3097. Additionally, several new rules have been created in https://github.com/elastic/detection-rules/pull/3112.

**Comment by Aegrah** [comment]
Moved to backlog until we gather additional telemetry from our UEBA changes.
