### ISSUE TITLE
[FR] Refactor Setup section in investigation guide to use `setup` field

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#3148]
## Summary

Per https://github.com/elastic/detection-rules/pull/3141#issuecomment-1739604781, we need to make changes to how we handle the Setup section in the investigation guide. We should make sure we dont incidentally introduce version lock bugs.

```[tasklist]
### Tasks
- [ ] Remove the build time field which parsed it out of investigation guide and moved it into setup
- [ ] Verify existing unit tests still apply
- [ ] Add a new unit test to ensure that the ### Setup category is no longer included in any investigation guides
```

**Comment by slawomirbabicz** [comment]
That renaming is destroying my custom setup extension... 
Also, you have the rules deployed already using that field "setup", but when creating rule using the API, eg:

`POST kbn://api/detection_engine/rules

{
...
"setup": "whatever"
...
}
`
results with error:

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "[request body]: invalid keys \"setup\""
} 
```

yet, the rules shipped contain that field already.

**Comment by slawomirbabicz** [comment]
Another problem is with different fields, like:

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "[request body]: Invalid value \"undefined\" supplied to \"new_terms_fields\",Invalid value \"undefined\" supplied to \"history_window_start\""
}
```



```
POST kbn://api/detection_engine/rules
{
    "author": [
        "Elastic"
    ],
    "description": "Identifies the use of a compression utility to collect known files containing sensitive information, such as credentials\nand system configurations.\n",
    "from": "now-9m",
    "index": [
        "auditbeat-*",
        "logs-endpoint.events.*",
        "endgame-*"
    ],
    "language": "kuery",
    "license": "Elastic License v2",
    "name": "Sensitive Files Compression customized_rule",
    "references": [
        "https://www.trendmicro.com/en_ca/research/20/l/teamtnt-now-deploying-ddos-capable-irc-bot-tntbotinger.html"
    ],
    "risk_score": 47,
    "rule_id": "776a9e98-71ad-48b8-aa4e-abe24449d483",
    "severity": "medium",
    "tags": [
        "Domain: Endpoint",
        "OS: Linux",
        "Use Case: Threat Detection",
        "Tactic: Collection",
        "Tactic: Credential Access",
        "Data Source: Elastic Endgame",
        "Data Source: Elastic Defend"
    ],
    "timestamp_override": "event.ingested",
    "type": "new_terms",
    "query": "event.category:process and host.os.type:linux",
    "threat": [
        {
            "framework": "MITRE ATT&CK",
            "technique": [
                {
                    "id": "T1552",
                    "name": "Unsecured Credentials",
                    "reference": "https://attack.mitre.org/techniques/T1552/",
                    "subtechnique": [
                        {
                            "id": "T1552.001",
                            "name": "Credentials In Files",
                            "reference": "https://attack.mitre.org/techniques/T1552/001/"
                        }
                    ]
                }
            ],
            "tactic": {
                "id": "TA0006",
                "name": "Credential Access",
                "reference": "https://attack.mitre.org/tactics/TA0006/"
            }
        },
        {
            "framework": "MITRE ATT&CK",
            "technique": [
                {
                    "id": "T1560",
                    "name": "Archive Collected Data",
                    "reference": "https://attack.mitre.org/techniques/T1560/",
                    "subtechnique": [
                        {
                            "id": "T1560.001",
                            "name": "Archive via Utility",
                            "reference": "https://attack.mitre.org/techniques/T1560/001/"
                        }
                    ]
                }
            ],
            "tactic": {
                "id": "TA0009",
                "name": "Collection",
                "reference": "https://attack.mitre.org/tactics/TA0009/"
            }
        }
    ]
}
```


Being unable to codify the rules and applying Git on it kind of discourages me to the product further usage, because it will be never-ending story chasing API changes, field renamings etc. 

I wish such rules (as well as other rules like monitoring) would be supported natively from Git somehow.
