### ISSUE TITLE
[Meta] Windows Detection Rules Tuning

### ISSUE THREAD

**Issue by w0rk3r** [elastic/detection-rules#3186]
## Summary

This Meta will focus on tuning the existing Windows rules, focusing on reducing the ruleset's general noise.

```[tasklist]
### Tasks
- [x] Analyze the rules for tuning opportunities
- [x] Evaluate whether to convert them to new_terms to reduce alert volume
- [x] PRs to Detection Rules
- [x] Check detection_rules issues for tuning requests
```

### Community Issues

* https://github.com/elastic/detection-rules/issues/2840
* https://github.com/elastic/detection-rules/issues/3081
* https://github.com/elastic/detection-rules/issues/3103
* https://github.com/elastic/detection-rules/issues/3104
* https://github.com/elastic/sdh-protections/issues/449
* https://github.com/elastic/detection-rules/issues/3357
* https://github.com/elastic/detection-rules/issues/3373

## PRs - First Iteration

* https://github.com/elastic/detection-rules/pull/3180
* https://github.com/elastic/detection-rules/pull/3181
* https://github.com/elastic/detection-rules/pull/3184
* https://github.com/elastic/detection-rules/pull/3185
* https://github.com/elastic/detection-rules/pull/3198
* https://github.com/elastic/detection-rules/pull/3209
* https://github.com/elastic/detection-rules/pull/3212
* https://github.com/elastic/detection-rules/pull/3214
* https://github.com/elastic/detection-rules/pull/3215
* https://github.com/elastic/detection-rules/pull/3229
* https://github.com/elastic/detection-rules/pull/3246

## PRs - 2nd Iteration (Sprint 11 & 12)

* https://github.com/elastic/detection-rules/pull/3344
* https://github.com/elastic/detection-rules/pull/3353
* https://github.com/elastic/detection-rules/pull/3354
* https://github.com/elastic/detection-rules/pull/3355
* https://github.com/elastic/detection-rules/pull/3359
* https://github.com/elastic/detection-rules/pull/3364
* https://github.com/elastic/detection-rules/pull/3367
* https://github.com/elastic/detection-rules/pull/3369

## PRs - 3rd Iteration (Sprint 13)

* https://github.com/elastic/detection-rules/pull/3376
* https://github.com/elastic/detection-rules/pull/3377
* https://github.com/elastic/detection-rules/pull/3380
* https://github.com/elastic/detection-rules/pull/3381
* https://github.com/elastic/detection-rules/pull/3382
* https://github.com/elastic/detection-rules/pull/3384
* https://github.com/elastic/detection-rules/pull/3385
* https://github.com/elastic/detection-rules/pull/3386
