### ISSUE TITLE
[Meta] Linux Rootkit Analysis & Rule dev

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#3210]
## Summary
Although we have many visibility issues in Linux right now, I would like to analyze several root/user mode root kits and write detections for their installation, persistence, defense evasion and connection activities. 

```[tasklist]
### Tasks
- [x] Identify 3 to 5 linux root kits that leverage different persistence and defense evasion methods (done)
- [x] Set up a demo environment to run these root kits (done)
- [x] Analyze these root kits (1 week)
- [x] Write detection rules  (1 week)
```

### Kworker-related
[[New Rule] Network Activity Detected via kworker](https://github.com/elastic/detection-rules/pull/3202)
[[New Rule & RTA] Shell Command Exec via kworker](https://github.com/elastic/endpoint-rules/pull/2891)
[[New Rule] Suspicious File Creation via Kworker](https://github.com/elastic/detection-rules/pull/3237)
[[New Rule] Suspicious Kworker UID Elevation](https://github.com/elastic/detection-rules/pull/3238)

### Kernel module load related
[[New BBR] Tainted Kernel Module Load](https://github.com/elastic/detection-rules/pull/3211)
[[New Rule] Out-Of-Tree Kernel Module Load](https://github.com/elastic/detection-rules/pull/3233)
[[New BBR] Kernel Driver Load](https://github.com/elastic/detection-rules/pull/3236)

### Misc.
[[New BBR] Reverse Connection through Port Knocking](https://github.com/elastic/detection-rules/pull/3219)
[[New Rule] Attempt to Clear Kernel Ring Buffer](https://github.com/elastic/detection-rules/pull/3217)
[[New BBR] Pot. Persistence Through Systemd-udevd](https://github.com/elastic/detection-rules/pull/3235)
[[New Rule] UID Elevation from Unknown Executable](https://github.com/elastic/detection-rules/pull/3239)
[[New BBR] Segfault Detected](https://github.com/elastic/detection-rules/pull/3240)

**Comment by Aegrah** [comment]
## [bds_lkm](https://github.com/bluedragonsecurity/bds_lkm)
Upon detonation, the following alerts were automatically triggered:
- Kernel Module Load Via insmod
- Suspicious File Creation in /etc for Persistence
- New systemd Service Created by Previously Unknown Executable

This rootkit has the functionality to delete the kernel logs through dmesg, the following logic is created to address for this gap:
`process where host.os.type == "linux" and event.action == "exec" and event.type == "start" and process.name == "dmesg" and process.args : "-c"`
Available at:

**Comment by Aegrah** [comment]
The following PRs were created based on rootkit research:
https://github.com/elastic/endpoint-rules/pull/2891
https://github.com/elastic/endpoint-rules/pull/2892
https://github.com/elastic/detection-rules/pull/3202

**Comment by Aegrah** [comment]
## [Reptile](https://github.com/f0rb1dd3n/Reptile)
Upon installation, the following new rule triggered:

- Tainted Kernel Module Load

We did not capture the installation of the reptile module. To address this gap, the following logic is created:
```
host.os.type:linux and event.dataset:"system.syslog" and process.name:kernel and 
message:"loading out-of-tree module taints kernel."
```



## While setting up a reverse connection, the following rules triggered:

A network event by a kernel worker thread is abnormal, hence the alert:

- Network Activity Detected via Kworker

Reptile leverages port knocking functionality, as such, the rule we created for the previous root kit triggered:

- Potential Linux Reverse Connection through Port Knocking

The root kit sets up a network connection as root, hence this rule triggered:

- Suspicious Network Connection Attempt by Root

And when running commands, they are executed through kworker as well, hence the following alert triggered:

- Shell Command Execution via Kworker

And Reptile creates a file under /dev/ptmx through kworker, hence the following alert triggers:

- Suspicious File Creation via kworker

## Reverse connection gaps
We did not capture the session escalation to root for the kworker process. To address this gap, the following logic was created:
```
process where host.os.type == "linux" and event.action == "session_id_change" and event.type == "change" and process.name : "kworker*"
```

**Comment by Aegrah** [comment]
## [reveng_rtkit](https://github.com/reveng007/reveng_rtkit)
Upon installation, the following DRs triggered:
- Kernel Module Load via insmod
- Attempt to Clear Kernel Ring Buffer
- Tainted Out-Of-Tree Kernel Module Load
- Tainted Kernel Module Load
- Kernel Driver Load

**Comment by Aegrah** [comment]
Finally, I experimented with:
- [Diamorphine](https://github.com/m0nad/Diamorphine)
- [Cerez](https://github.com/ngn13/cerez)
- [B4rnd00r](https://github.com/khale/kernel-rootkit-poc)
- [Brokepkg](https://github.com/R3tr074/brokepkg)
But did not find any additional coverage gaps that we are capable of detecting. Many of the actions conducted by the rootkits remain undetectable, as we see 0 logs, even with auditd_manager, monitoring the syscall level. 

Next up, a Meta relating eBPF rootkits could be interesting, but I am afraid we also do not capture the necessary data to detect these either.

**Comment by brokensound77** [comment]
is this complete?

**Comment by Aegrah** [comment]
The last PR related to this Meta has been merged a few minutes ago, will close out the Meta! @brokensound77
