### ISSUE TITLE
[Meta] Linux Investigation Guides - Part 2

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#3269]
## Summary
This is part 2 of the "add 10 new Linux IGs per sprint" resolution. I will be adding 10 new investigation guides with OSQuery extension this sprint. 

The following tasks have been or are to be performed:
```[tasklist]
### Tasks
- [x] Creation of C2 Linux IGs
- [x] PR review of C2 Linux IGs/Merge
- [x] Creation of set 1 - Persistence Linux IGs
- [x] PR review/merge of set 1 - Persistence Linux IGs
- [x] Creation of set 2 - Persistence Linux IGs
- [ ] PR review/merge of set 2 - Persistence Linux IGs
- [x] Present feedback on GenAI IG creation work
```

Additionally, while working on these IGs, @Mikaayenson 's generative AI IG creation work will be used. And feedback on these IGs will be added to https://github.com/elastic/elastic-genai-rulecraft/issues/5.

Feedback was presented in https://docs.google.com/document/d/1Xb6-XeMKEqecDgMTmstMks2Gsd12rkbVf0wvOwISXD8/edit

**Comment by Aegrah** [comment]
First PR with 4 new IGs for Linux Persistence related rules has been created: https://github.com/elastic/detection-rules/pull/3288. The next 6 will be added after PTO.

**Comment by Aegrah** [comment]
I will finish out the final IGs, this week. There has been slippage due to unexpected PTO.

**Comment by terrancedejesus** [comment]
@Aegrah - Any chance we can get a tasklist in here to track the great work you have done and are going to finish? Will help with tracking at a higher level and correlation from meta -> issues (if applicable) -> PRs.

**Comment by Aegrah** [comment]
```[tasklist]
### Tasks
- [x] Creation of C2 Linux IGs
- [ ] PR review of C2 Linux IGs/Merge
- [x] Creation of set 1 - Persistence Linux IGs
- [x] PR review/merge of set 1 - Persistence Linux IGs
- [ ] Creation of set 2 - Persistence Linux IGs
- [ ] PR review/merge of set 2 - Persistence Linux IGs 
```

**Comment by Aegrah** [comment]
The second PR was created: https://github.com/elastic/detection-rules/pull/3350. Now all that is left, are reviews.

**Comment by Aegrah** [comment]
As the only thing that is left are the reviews, this meta will be closed.
