### ISSUE TITLE
[Meta] Linux Malware Research Setup

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#3286]
## Summary
In order to do good Linux malware research, and find malicious behavior that is endpoint-rule worthy, I want to focus more on malware analysis, rather than attack/technique/tactic analysis. This Meta focuses on setting up a proper Linux malware research lab, collect a set of Linux malware samples that are interesting to analyze, dive into yara, and more.

```[tasklist]
### Tasks
- [ ] Set up a proper VMWare local malware testing cluster.
- [ ] Research into good Linux malware sources on X, research papers and other sources.
- [ ] Dive into Yara, and see how this can help me with finding specific new samples on VT.
- [ ] ... More will be added along the way.
```

**Comment by Aegrah** [comment]
Sources to read through:
- https://sandflysecurity.com/blog/bpfdoor-an-evasive-linux-backdoor-technical-analysis/

**Comment by Aegrah** [comment]
This meta will be closed, due to overlap with other projects such as the FirstCTI24 workshop project.
