### ISSUE TITLE
[Meta] Review Google Chrome Logs Data for Potential Browser-Based Detections Rules

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#3325]
## Meta Summary

This meta is used to track the review of Google Chrome Log ingestion into the Elastic Stack via the Google Workspace integration. Google Chrome logs are available from the Reports: Admin API endpoint in Google Workspace. This potentially grants visibility into end user behavior via the browser that could be used to detect browser-based threats.

This meta is meant to only capture the triage and exploration of this. If viable, another meta will be created and scoped accordingly to add additional detection rules.

## Estimated Time to Complete
1 Week

## Tasklist

```[tasklist]
### Meta Tasks
- [ ] Provide Week 1 Update Comment
- [ ] Provide Week 2 Update or Closeout Comment
- [ ] Setup Google Workspace Lab
- [ ] Add Several Temporary Users
- [ ] Setup Google Chrome Monitoring from Admin Console
- [ ] Emulate Legitimate and Malicious Behavior
- [ ] Review Ingested Data and Data Model for Plausible Data Points to Write Detection Rules On
- [ ] Create Next Meta (if applicable)
```

## Resources / References
* https://support.google.com/a/answer/9393909?hl=en
* https://docs.elastic.co/en/integrations/google_workspace

**Comment by terrancedejesus** [comment]
Closing this issue as it is currently out of scope for TRADE's cloud threat research.

**Comment by imays11** [comment]
Closing for now. The direction is still valid (google_workspace.chrome is in the integration and we have no Chrome-based rules), but this exploratory meta never moved forward and GWS effort is better spent on higher-priority prebuilt rule gaps we can ship today. Happy to create a new meta when we're ready to scope Chrome detections properly.
