### ISSUE TITLE
[Meta] Update Prebuilt Detection Rules Release Process

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#3374]
## Meta Summary

Importance: Reduce time-to-release by fixing tools and processes for the release workflow that do not currently work. A list of these has been included below, along with a summary of what needs to be resolved.

- Release Fleet Workflow (`release-fleet.yml`) - Needs to be reviewed for reliability. Does not handle exceptions for branches such as 8.10. Needs arguments to target backport branches in integrations.
- Release Docs Workflow (`release-docs.yml`) - Needs to be reviewed for reliability. Code logic should take into account ASCII doc URL formatting or broken links, deprecated rule handling and new minor release pages with main as base.
- Updated release docs

## Estimated Time to Complete
~2 weeks

## Potential Blockers
No potential blockers for this meta.

## Tasklist
Another tasklist will be created as each bug is identified and analyzed.

```[tasklist]
### Meta Tasks
- [x] Provide Week 1 Update Comment
- [ ] Provide Week 2 Update or Closeout Comment
- [ ] https://github.com/elastic/detection-rules/pull/3403
```

**Comment by terrancedejesus** [comment]
#### Review release-fleet workflow for updates and bugs
The [release fleet](https://github.com/elastic/detection-rules/blob/main/.github/workflows/release-fleet.yml) workflow needs to be reviewed. There were changes to how we push package updates to the Integrations repository that may need to be addressed in this workflow. We may also be able to simplify this process by automatically obtaining the last locked version commit hash for each branch, rather than relying on the workflow input.

An `extract-commit-hash` job can be added to this workflow in place of the `check-commit` job. The original job relied on the engineer to find the SHA commit hash from the lock versions workflow that commits to each protected branch when version lock changes are merged into main. Since our `release-fleet` workflow runs from each branch, it should be able to use `git log --grep` to filter for that commit and choose the latest, then carry this forward in the next job. We then need to make adjustments in the `fleet-pr` job to reconcile whats carried from the previous.

```
    extract-commit-hash:
      name: Extract Commit Hash
      runs-on: ubuntu-latest
      outputs:
        commit_hash: ${{ steps.extract_commit_hash.outputs.commit_hash }}
      steps:
        - name: Checkout detection-rules
          uses: actions/checkout@v3
          with:
            path: detection-rules
            fetch-depth: 0

        - name: Extract commit hash
          id: extract_commit_hash
          run: |
            cd detection-rules
            COMMIT_HASH=$(git log --grep="Lock versions for releases" -1 --format="%H")
            echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          shell: bash
```

**Comment by terrancedejesus** [comment]
**Adjust `packages.yml` in 8.10 branch so `kibana.version` is `8.10.1`**
Elastic stack version `8.10.0` had a severe vulnerability which caused package registry team to only allow `8.10.1` and up deployments to run for `8.10` integration packages. As a result, when we push `8.10.x` rule packages to integrations for updated, the manifest (built from the `registry_data` in `packages.yml`) needs to be `8.10.1`. This is specifically the `conditions` > `kibana.version` field value. By default, this is how Fleet determines which integration versions are compatible with which stack versions. We always make the patch `.0` when we create a new branch. However, the `8.10` branch needs to be changed from `8.10.0` to `8.10.1`. If not, the build will fail upstream in the integrations repository when built.

```yaml
  registry_data:
    categories:
    - security
    conditions:
      kibana.version: ^8.13.0
      elastic:
        subscription: basic
    description: Prebuilt detection rules for Elastic Security
    format_version: 3.0.0
    icons:
    - size: 16x16
      src: /img/security-logo-color-64px.svg
      type: image/svg+xml
    source:
      license: Elastic-2.0
    name: security_detection_engine
    owner:
      github: elastic/protections
      type: elastic
    title: Prebuilt Security Detection Rules
    type: integration
    version: 8.13.0-beta.0
```

Additionally, an important consideration is when we add historical rules, we used to rely on `name` from `packages.yml` to help query the EPR API for historical releases. The `name` in each `packages.yml` for each branch reflects the branch stack version. If we use `8.10` to query EPR, it will not return packages pushed that are compatible with `8.10.1`. Thus when doing `build-release` CLI command now, we pass the value of `kibana.version` from `packages.yml` instead. Once we update the branch so this value is `8.10.1` we will not need to make any adjustments in the other methods that query the EPR API.

```python
    if add_historical:
        previous_pkg_version = find_latest_integration_version("security_detection_engine", "ga",
                                                               registry_data['conditions']['kibana.version'].strip("^"))
        sde = SecurityDetectionEngine()
        historical_rules = sde.load_integration_assets(previous_pkg_version)
        historical_rules = sde.transform_legacy_assets(historical_rules)

        docs = IntegrationSecurityDocsMDX(config['registry_data']['version'], Path(f'releases/{config["name"]}-docs'),
                                          True, historical_rules, package, note=update_message)
        docs.generate()

        click.echo(f'[+] Adding historical rules from {previous_pkg_version} package')
        package.add_historical_rules(historical_rules, config['registry_data']['version'])
```

To resolve this we need to checkout `8.10` branch, update the kibana version and push manually.

**Comment by terrancedejesus** [comment]
## Update 01-26-2024
We have made progress with updating the Detection Rules release process, ultimately addressing bugs and exceptions that were introduced from changes upstream. Please review to the tasklist of this issue to view which has been addressed so far.

Moving forward, we should have the bugs and exceptions addressed in the linked pull request. We will need to still review https://github.com/elastic/detection-rules/pull/2807, make updates and merge accordingly, once done, this issue can be marked as complete.

**Comment by terrancedejesus** [comment]
## Update 02-06-2024
This issue has been re-opened. It was closed due to the only linked pull request being merged, however, changes still need to occur.

- Update `build-release` CLI command to exclude doc generation unless explicitly flagged
- Update security doc generation to create correct ASCII doc links
- Test changes after merging in lock versions PR

The detection rules release has been started with @shashank-elastic.
