### ISSUE TITLE
[FR] Adds alerts Suppression to threshold rule

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#3393]
## Summary

Upstream Kibana opened this PR https://github.com/elastic/kibana/pull/171423. 

We need to review the schemas and add support accordingly. 

```[tasklist]
### Tasks
- [x] Resolve any schema changes that
- [x] Update any `TestAlertSuppression` unit tests.
- [x] Add support for the threshold alertsupression fields.
```

**Comment by Mikaayenson** [comment]
## Idea for notifications

@brokensound77 had an idea to create a DAG to ideally get early notifications for kibana PRs that touch files we need to track.
