### ISSUE TITLE
[Bug] Cleanup test_event_override unit test

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#3394]
## Summary

With the recent [PR](https://github.com/elastic/detection-rules/pull/3368) to update the test_event_override unit test, it introduced a couple issues.

- Backports failed https://github.com/elastic/detection-rules/actions/runs/7560689292 due to forked rules not receiving the updates. Usually this is business as usual if we address immediately after merging the PR and open a maintenance window. The failing checks in this case were caught the next day.
- Fields unused in the test:

```python
rule_integrations = rule.contents.metadata.get('integration')
if isinstance(rule_integrations, str):
   rule_integrations = [rule_integrations]
```
- Finally checking literal in query `"sequence" in rule_query` vs using the built in method `rule.contents.data.is_sequence`. 

```[tasklist]
### Tasks
- [x] Fix backports: [8.3](https://github.com/elastic/detection-rules/actions/runs/7573522769), [8.4](https://github.com/elastic/detection-rules/actions/runs/7573406078), [8.5](https://github.com/elastic/detection-rules/actions/runs/7573166539), [8.6](https://github.com/elastic/detection-rules/actions/runs/7573118746), [8.7](https://github.com/elastic/detection-rules/actions/runs/7572970303), [8.8](https://github.com/elastic/detection-rules/actions/runs/7572871678),
- [x] Fix backports: [8.9](https://github.com/elastic/detection-rules/actions/runs/7572739554) (separated due to line length)
- [ ] https://github.com/elastic/detection-rules/pull/3395
```
