### ISSUE TITLE
[Meta] Linux Tuning & Index Pattern Checks

### ISSUE THREAD

**Issue by Aegrah** [elastic/detection-rules#3428]
## Meta Summary
Placeholder for detection_rules tuning next sprint. Many of the new Linux rules currently do not leverage all potential indices. While doing performance analysis and tuning, my second goal is to ensure that the rules compatible with other data sources (endgame, auditbeat, auditd_manager) will be added to the rule index list. 

## Estimated Time to Complete
2 - 3 days, depending on how much time is being spent on it. This meta will be one that can be worked at whenever some additional time is available. 

## Potential Blockers
None.

## Tasklist

```[tasklist]
### Meta Tasks
- [ ] Review Linux Detection Rules 
- [ ] Create Linux Detection Rules Tuning PR
- [ ] Review Linux Cross-Platform Rules 
- [ ] Create Linux Cross-Platform Tuning PR
- [ ] Review Linux Building Block Rules 
- [ ] Create Linux Building Block Rules Tuning PR
- [ ] Review Linux Endpoint Rules 
- [ ] Create Linux Endpoint Rules Tuning PR
```

**Comment by Aegrah** [comment]
## Setup
In order to integrate auditd_manager seamlessly, we prepared for this issue by getting #3430 in. This PR removes the check for the `event.action == "auditd_manager.auditd"`, allowing us to make the rules compatible. 

In #3451 the event.action field was removed from all auditd_manager queries, and the "Data Source: Auditd Manager" tag was added.

**Comment by Aegrah** [comment]
## Rules that require additional research & tuning
- [discovery_virtual_machine_fingerprinting.toml](https://github.com/elastic/detection-rules/blob/538fc8c4dd4edd974facec658cd41670b6267919/rules/linux/discovery_virtual_machine_fingerprinting.toml)
- [execution_remote_code_execution_via_postgresql.toml](https://github.com/elastic/detection-rules/blob/538fc8c4dd4edd974facec658cd41670b6267919/rules/linux/execution_remote_code_execution_via_postgresql.toml)
-[execution_shell_evasion_linux_binary.toml](https://github.com/elastic/detection-rules/blob/538fc8c4dd4edd974facec658cd41670b6267919/rules/linux/execution_shell_evasion_linux_binary.toml)
-
