### ISSUE TITLE
[Meta] Address Non-Performant Rules with Wildcard Usage

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#3473]
## Parent Epic (If Applicable)

* https://github.com/elastic/ia-trade-team/issues/282

## Meta Summary

There are several rules that could use review and tunings for performance. Tuning suggestions are purely performance-based where unnecessary wildcard usage is used. Other performance considerations may be the following:

* EQL rule with generic first sequence
* EQL rule with no maxspan defined for sequence
* Consider removing sequence if plausible

As suggested internally, we will rely on other built-in functions for EQL to tune for performance. Wildcards will stay in certain sections of the query if necessary.

For each rule we should attempt to test them against available telemetry stacks for performance increase or decreases. Note that this does not accurately reflect any specific customer but will be used to performance impact from functionality adjustments.

## Tasklist

```[tasklist]
### Meta Tasks
- [x] Updated each rule with a performance note
- [ ] https://github.com/elastic/detection-rules/issues/3423
- [ ] https://github.com/elastic/detection-rules/pull/3478
- [ ] https://github.com/elastic/detection-rules/pull/3479
- [ ] https://github.com/elastic/detection-rules/pull/3480
- [ ] https://github.com/elastic/detection-rules/pull/3481
- [ ] https://github.com/elastic/detection-rules/pull/3483
- [ ] https://github.com/elastic/detection-rules/pull/3484
- [ ] https://github.com/elastic/detection-rules/pull/3482
- [ ] https://github.com/elastic/detection-rules/pull/3485
```

Rule List:

- [AdminSDHolder SDProp Exclusion Added](https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_sdprop_exclusion_dsheuristics.toml)
- [A scheduled task was created](https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_scheduled_task_creation_winlog.toml)
- [A scheduled task was updated](https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_scheduled_task_updated.toml)
- [Potential Credential Access via DCSync](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_dcsync_replication_rights.toml)
- [Access to Sensitive LDAP Attribute](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_ldap_attributes.toml)
- [Potential Credential Access via DuplicateHandle in LSASS](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_potential_lsa_memdump_via_mirrordump.toml)
- [Potential Credential Access via LSASS Memory Dump](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_suspicious_lsass_access_memdump.toml)
- [Potential Credential Access via Renamed COM+ Services DLL](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_suspicious_comsvcs_imageload.toml)
- [Temporarily Task Creation](https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_temp_scheduled_task.toml)
- [Suspicious LSASS Access via MalSecLogon](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_lsass_handle_via_malseclogon.toml)
- [SeDebugPrivilege Enabled by a Suspicious Process](https://github.com/elastic/detection-rules/blob/main/rules/windows/privilege_escalation_tokenmanip_sedebugpriv_enabled.toml)
- [Interactive Terminal Spawned via Python](https://github.com/elastic/detection-rules/blob/main/rules/linux/execution_python_tty_shell.toml)
- [Multiple Logon Failure Followed by Logon Process](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_bruteforce_multiple_logon_failure_followed_by_success.toml)
- [Potential Malicious File Downloaded from Google Drive](https://github.com/elastic/detection-rules/blob/main/rules/cross-platform/command_and_control_google_drive_malicious_file_download.toml)
- [Multiple Logon Failure Followed by Logon Success](https://github.com/elastic/detection-rules/blob/main/rules/windows/credential_access_bruteforce_multiple_logon_failure_followed_by_success.toml)
- [Suspicious Renaming of ESXI Files](https://github.com/elastic/detection-rules/blob/main/rules/linux/defense_evasion_rename_esxi_files.toml)
- [Persistence via WMI Standard Registry Provider](https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_via_wmi_stdregprov_run_services.toml)
- [Direct Outbound SMB Connection](https://github.com/elastic/detection-rules/blob/main/rules/windows/lateral_movement_direct_outbound_smb_connection.toml)
- [Account Password Reset Remotely](https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_remote_password_reset.toml)
- [Component Object Model Hijacking](https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_suspicious_com_hijack_registry.toml)
- [SIP Provider Modification](https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_sip_provider_mod.toml)
- [Uncommon Registry Persistence Change](https://github.com/elastic/detection-rules/blob/main/rules/windows/persistence_registry_uncommon.toml)
- [Remote File Creation on Sensitive Directory](https://github.com/elastic/detection-rules/blob/main/rules/cross-platform/lateral_movement_remote_file_creation_in_sensitive_directory.toml)
- [Potential Linux Ransomware Note Creation Detected](https://github.com/elastic/detection-rules/blob/main/rules/linux/impact_potential_linux_ransomware_note_detected.toml)
- [Remote Computer Account DnsHostName Update](https://github.com/elastic/detection-rules/blob/main/rules/windows/privilege_escalation_suspicious_dnshostname_update.toml)
- [Suspicious File Changes Activity Detected](https://github.com/elastic/detection-rules/blob/main/rules/linux/impact_potential_linux_ransomware_file_encryption.toml)
- [Abnormal Process ID or Lock File Created](https://github.com/elastic/detection-rules/blob/main/rules/linux/execution_abnormal_process_id_file_created.toml)

**Comment by terrancedejesus** [comment]
Update 03-03-2024

* All rules shared from SDH have been reviewed and adjusted, with draft pull requests for each
* As intended, each query was reviewed for a list of performance checks that are listed below
* Note - each pull request is in draft until we can identify performance changes accurately
    * Each query was EQL and we do not have an EQL profiler to assess performance changes introduced, our initial changes are based on the assumption of EQL functions vs wildcard usage where wildcard usage is more expensive
* Global alert telemetry was reviewed for each rule in an attempt to identify efficacy tuning by removing false-positives or making query adjustments
* Comments were added to each query in an attempt to better explain the logic, especially if complex
* `### Performance` headers were added where an investigation guide existed. Content beneath this was added to explain potential performance impact of the rule and why according to the logic
* `note` was added to each rule where it did not exist prior to. The value added explained potential performance impact fo the rule and why according to the logic

**Comment by terrancedejesus** [comment]
Update 03-04-2024

While we await feedback from the query team, we were introduced to https://github.com/elastic/rally which may help us benchmark the searches for each rule adjustment we have done so far. This will help us determine if adjustments are more performant or not. We will move on to testing this while we await feedback.

**Comment by terrancedejesus** [comment]
Update 03-27-2024

* The rule performance concerns that relate to these rules has been solved via architecture adjustments to the customers ingestion, shard allocation and more
* We have unsuccessfully been able to conclude that changing from asterisks to EQL functions where plausible increases performance when the rule is executed due to a lack of benchmarking and performance testing options for EQL
* This issue is no longer tied directly to the urgent SDH and will be treated as a meta to tune several rules for not only performance, but false-positives as well.
* Rules will need to be revisited, re-ran and the appropriate details shared within each pull request before requesting review.
