### ISSUE TITLE
[Meta] Explore Detection Opportunities on Active Directory Relay, Spoofing and Coercion Attacks - Part 1

### ISSUE THREAD

**Issue by w0rk3r** [elastic/detection-rules#3544]
## Parent Epic (If Applicable)

https://github.com/elastic/ia-trade-team/issues/276

## Summary

Explore how attackers can exploit Active Directory for Credential Access using Relay, spoofing and coercion attacks.

```[tasklist]
### Tasks
- [x] Build a Lab
- [x] Explore ADIDNS Spoofing
- [x] Explore WSUS Spoofing
- [x] Explore Coercion Attacks
- [ ] Explore PowerShell Tooling
```

## Goals

- Improve coverage for these attacks.
- Gain better knowledge of AD DS.

## Resources:

* https://www.netspi.com/blog/technical/network-penetration-testing/exploiting-adidns/
* https://www.netspi.com/blog/technical/network-penetration-testing/adidns-revisited/
* https://www.thehacker.recipes/a-d/movement/mitm-and-coerced-authentications
* https://mayfly277.github.io/categories/ad/
* https://www.akamai.com/blog/security-research/spoofing-dns-by-abusing-dhcp
* https://www.youtube.com/watch?v=u-RsFCXMqfk
* https://www.microsoft.com/en-us/security/blog/2023/03/24/guidance-for-investigating-attacks-using-cve-2023-23397/

### PRs

* https://github.com/elastic/detection-rules/pull/3535
* https://github.com/elastic/detection-rules/pull/3539
* https://github.com/elastic/detection-rules/pull/3543
* https://github.com/elastic/detection-rules/pull/3734
* https://github.com/elastic/detection-rules/pull/3748
* https://github.com/elastic/detection-rules/pull/3908
* https://github.com/elastic/detection-rules/pull/3912
* https://github.com/elastic/detection-rules/pull/3916
* https://github.com/elastic/detection-rules/pull/3917
* https://github.com/elastic/detection-rules/pull/3928

**Comment by w0rk3r** [comment]
Closing this one as completed. I explored and read a lot of things that for sure will require more cycles to explore. I'll open follow-up issues.
