### ISSUE TITLE
[Meta] Refactor Rule Loader and Validation for Optimizations

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#3556]
## Parent Epic (If Applicable)

https://github.com/elastic/security-team/issues/8718

## Meta Summary

The detection rules loader is extremely slow. While we're planning on tackling the loader for potential optimizations, we should clean up some of the warnings and error messages. 

## Estimated Time to Complete
1-2 sprints

## Potential Blockers

None

## Tasklist

```[tasklist]
### Meta Tasks
- [ ] Provide Week 1 Update Comment
- [ ] Provide Week 2 Update or Closeout Comment
- [ ] https://github.com/elastic/detection-rules/issues/2609
- [ ] https://github.com/elastic/detection-rules/issues/2606
- [ ] https://github.com/elastic/detection-rules/issues/3195
```

## Resources / References

May be related to the work completed in https://github.com/elastic/detection-rules/issues/3512
