### ISSUE TITLE
[Meta] Refactor Rule Formatter

### ISSUE THREAD

**Issue by Mikaayenson** [elastic/detection-rules#3558]
## Parent Epic (If Applicable)

https://github.com/elastic/security-team/issues/8718

## Meta Summary

The formatter was once written when the schemas were flat structures. Now that they have evolved to nested structures, the rule formatter should be refactored. 
- The new solution should easily be able to specify the order of the toml file.
- The solution should remain consistent and not unintentionally create new sha256 calculations.
- The solution should still support some of the old features:
  - text wrapping after a certain character limit
  - skipping fields that should not be formatted or normalized
  
## Tasklist

```[tasklist]
### Meta Tasks
- [ ] Provide Week 1 Update Comment
- [ ] Provide Week 2 Update or Closeout Comment
- [ ] Leverage tomlkit to refactor how we format our toml rules
- [ ] Develop a CLI command to validate all existing toml files and reformat (lint)
- [ ] Ensure all rules have 
- [ ] Add unit tests for the formatter 
```

**Comment by shashank-elastic** [comment]
Edge case of formatter failing on nested fields as illustrated in https://github.com/elastic/detection-rules/pull/3681#issuecomment-2121740607
