### ISSUE TITLE
[FR] New Terms Suppression Schema Updates

### ISSUE THREAD

**Issue by eric-forte-elastic** [elastic/detection-rules#3640]
## Summary

We should update the schemas as need based on the addition of New Terms suppression support in 8.14. 

See [Slack](https://elastic.slack.com/archives/C02USDK55AQ/p1713869846653969) for context. 

Additionally, suppression for ML, EQL (sequence), EQL (non-sequence), and ESQL are planned for 8.15 and we should track this as well. 

## Tasks

```[tasklist]
#### PR Checklist
- [ ] Link to the relevant Kibana PR or issue provided
- [ ] Exported detection rule(s) from Kibana to showcase the feature(s)
- [ ] Converted the exported ndjson file(s) to toml in the detection-rules repo
- [ ] Re-exported the toml rule(s) to ndjson and re-imported into Kibana
- [ ] Updated necessary unit tests to accommodate the feature
- [ ] Applied min_compat restrictions to limit the feature to a specified minimum stack version
- [ ] Executed all unit tests locally with a test toml rule to confirm passing
- [ ] Included Kibana PR implementer as an optional reviewer for insights on the feature
- [ ] Implemented requisite downgrade functionality
- [ ] Cross-referenced the feature with product documentation for consistency
- [ ] Incorporated a comprehensive test rule in unit tests for full schema coverage
- [ ] Conducted system testing, including fleet, import, and create APIs
```

## Dependencies and Constraints

...
