### ISSUE TITLE
[Meta] Add Auth0 Prebuilt Threat Detection Ruleset

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/detection-rules#3780]
## Parent Epic (If Applicable)
* https://github.com/elastic/ia-trade-team/issues/271

## Meta Summary

Auth0 is a third-party authentication and authorization platform that allows developers to add these services to their applications. Auth0 can be used to secure web and mobile applications, and works with a variety of programming languages and APIs.  This meta aims to explore the Auth0 integration, dataset and rule development for authentication/authorization.

Note - This request stems from a recent Okta [publication](https://sec.okta.com/articles/2024/05/detecting-cross-origin-authentication-credential-stuffing-attacks) that highlights event logs from Auth0 that could be used to identify credential stuffing against CORS.

## Estimated Time to Complete
2 weeks

## Potential Blockers
* Licensing availability
* https://github.com/elastic/integrations/issues/10139

## Tasklist

```[tasklist]
### Meta Tasks
- [ ] Provide Week 1 Update Comment
- [ ] Provide Week 2 Update or Closeout Comment
- [ ] Create Auth0 account and setup integration
- [ ] Explore dataset and design 5-10 detection rules for OOTB
- [ ] https://github.com/elastic/detection-rules/issues/3769
```

## Resources / References
* https://owasp.org/www-community/attacks/Credential_stuffing
* https://auth0.com/docs/secure/attack-protection
* https://gluu.org/autho-hack/
* https://auth0.com/docs/secure/attack-protection/breached-password-detection
* https://medium.com/@iamkushimo/how-auth0-an-authenticator-service-provider-was-hacked-and-what-it-means-for-the-future-of-648f05a483d1
* https://sentorsecurity.com/blog/vulnerability-disclosure-authentication-bypass-in-auth0/
* https://amjadali110.medium.com/how-i-exploited-an-auth0-misconfiguration-to-bypass-login-restrictions-c5d8c20d5505
* https://owasp.org/www-community/attacks/Credential_stuffing

**Comment by terrancedejesus** [comment]
#### Update 06-12-2024
Attempting to setup the Auth0 integration with Elastic is too cumbersome in it's current state. Built ~2 years ago, the log ingestion requires a custom webhook in Auth0 -> POST requests to a custom HTTP server API with a proxy and valid TLS certificate for the agent to ingest the logs. We have created an issue to request an update to the integration before continuing.

Ref: https://github.com/elastic/integrations/issues/10139

**Comment by terrancedejesus** [comment]
Closing this issue as it is currently out of scope for TRADE's cloud threat research.
