### ISSUE TITLE
[Meta] Evaluate moving PowerShell Rules to ES|QL

### ISSUE THREAD

**Issue by w0rk3r** [elastic/detection-rules#4095]
## Summary

Interacting with PowerShell logs has been complicated for a long time, as EQL [doesn't support](https://github.com/elastic/eql/issues/17) text fields. For them to work with KQL, we needed to adjust field types, analyzers, etc. Then in 8.12 we had bugs in how KQL parses backslashes & wildcards and had to adapt and use Query DSL for exceptions.

This issue aims to evaluate whether using ES|QL and the `TO_LOWER` function can simplify rule writing and maintenance/tuning.

### Estimated Time to Complete

1 week

### Potential Blockers

- ES|QL handling of backslashes and wildcards
- https://github.com/elastic/detection-rules/pull/3505

### Tasking

```[tasklist]
### Meta Tasks
- [x] Convert sample queries and test with PowerShell data
- [x] Evaluate if `min_stack` is needed for ES|QL functions or language changes
- [ ] Convert rules and exceptions
- [ ] PR to detection rules
```

### Potential References

- https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-to_lower
- https://github.com/elastic/integrations/issues/1776

**Comment by w0rk3r** [comment]
I've tested three approaches: Using the LIKE operator and the MATCH and QSTR functions to interact with the PowerShell logs.

A bit more of context can be found on our internal Slack [here](https://elastic.slack.com/archives/C02TBFZFYSD/p1737125294283619). But here is what we tested for community visibility:

# What I've Tested That Showed Potential:

## Using the `LIKE` Operator
- **Pros:**
  - Production-Ready
  - Case-insensitive behavior
  - Supports wildcards
- **Cons:**
  - Performance intensive:
    - Test query took **1865ms** (against 371ms in KQL)
    - Example:
      ```sql
      FROM logs-windows.powershell* 
      WHERE host.os.type == "windows" 
      AND powershell.file.script_block_text LIKE "*System.Reflection.*"
      ```
  - Wildcard usage is required, which has performance implications.

---

## Using `QSTR`
- **Pros:**
  - Case-insensitive behavior
  - Limited wildcard support
  - Performant:
    - Test query took **147ms** (against 371ms in KQL)
    - Example:
      ```sql
      FROM logs-windows.powershell* 
      WHERE host.os.type == "windows" 
      AND qstr("powershell.file.script_block_text : 'System.Reflection.*'")
      ```
- **Cons:**
  - **Tech Preview**
  - Wildcards don't work with partial keywords:
    - `System.Reflection.*` matches `System.Reflection.Assembly`, but `System.Reflection.Asse*` doesn't, which limits the use cases.
  - OR condition limitation
  - Ignores special characters

---

## What I've Tested That Didn't Work:

### Using the `MATCH` Operator/Function
- Breaks the searched term into OR conditions, causing unintended matches:
  - Example:
    ```sql
    powershell.file.script_block_text : "Reflection.TypeAttributes"
    ```
    Acts as:
    ```sql
    powershell.file.script_block_text : "Reflection" OR powershell.file.script_block_text : "TypeAttributes"
    ```
- OR condition limitation

**Comment by w0rk3r** [comment]
We decided to not move existing rules from KQL but introduce ES|QL in PowerShell rules where KQL would not suffice.
